/**
 * Downloads the self-hosted webfonts into public/fonts/ and generates
 * src/styles/fonts.css from what actually came back.
 *
 * Run once (or when changing families):  node scripts/fetch-fonts.mjs
 *
 * We self-host rather than hotlink Google Fonts. Hotlinking leaks every
 * visitor's IP to a third party, which a German court has already ruled
 * against, and it makes the site's typography depend on someone else's
 * uptime. Instrument Sans is SIL Open Font License, so redistribution is fine.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const OUT_FONTS = 'public/fonts';
const OUT_CSS = 'src/styles/fonts.css';

// A modern desktop UA, so the API serves variable woff2 rather than legacy formats.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';

const FAMILIES = [
  {
    name: 'Instrument Sans',
    file: 'instrument-sans',
    url: 'https://fonts.googleapis.com/css2?family=Instrument+Sans:ital,wght@0,400..700;1,400..700&display=swap',
  },
];

// We only ship Latin. latin-ext carries the Turkish and German characters
// this site actually needs (Ö, ü, ğ, ş, ç, ı in "Özer", "München", "Würzburg").
const WANTED = new Set(['latin', 'latin-ext']);

await mkdir(OUT_FONTS, { recursive: true });

const blocks = [];

for (const fam of FAMILIES) {
  const res = await fetch(fam.url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${fam.name}: font CSS request failed (${res.status})`);
  const css = await res.text();

  // Each @font-face is preceded by a /* subset */ comment.
  const chunks = css.split('/*').slice(1);
  let kept = 0;

  for (const chunk of chunks) {
    const subset = chunk.slice(0, chunk.indexOf('*/')).trim();
    if (!WANTED.has(subset)) continue;

    const src = chunk.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
    const range = chunk.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
    const style = /font-style:\s*italic/.test(chunk) ? 'italic' : 'normal';
    const weight = chunk.match(/font-weight:\s*([^;]+);/)?.[1]?.trim() ?? '400';
    if (!src || !range) continue;

    const filename = `${fam.file}-${subset}-${style}.woff2`;
    const bin = await fetch(src, { headers: { 'User-Agent': UA } });
    if (!bin.ok) throw new Error(`${filename}: download failed (${bin.status})`);
    const buf = Buffer.from(await bin.arrayBuffer());
    await writeFile(join(OUT_FONTS, filename), buf);
    kept++;

    blocks.push(
      `@font-face {\n` +
        `  font-family: "${fam.name}";\n` +
        `  font-style: ${style};\n` +
        `  font-weight: ${weight};\n` +
        `  font-display: swap;\n` +
        `  src: url("/fonts/${filename}") format("woff2");\n` +
        `  unicode-range: ${range};\n` +
        `}`
    );
    console.log(`  ${filename}  ${(buf.length / 1024).toFixed(1)} KB`);
  }
  if (!kept) throw new Error(`${fam.name}: no matching subsets found`);
  console.log(`${fam.name}: ${kept} file(s)`);
}

const header =
  `/* GENERATED by scripts/fetch-fonts.mjs - do not edit by hand.\n` +
  `   Newsreader and Inter, SIL Open Font License 1.1.\n` +
  `   Re-run the script to regenerate. */\n\n`;

await writeFile(OUT_CSS, header + blocks.join('\n\n') + '\n');
console.log(`\nwrote ${OUT_CSS} (${blocks.length} @font-face rules)`);
